multiClusterObservability:
  include: false
  createNamespace: true
  name: observability
  namespace: open-cluster-management-observability
  enableDownsampling: true
  alertmanagerStorageSize: 1Gi
  compactStorageSize: 50Gi
  receiveStorageSize: 50Gi
  ruleStorageSize: 50Gi
  storeStorageSize: 50Gi
  observabilityAddonSpec:
    interval: 300
    scrapeSizeLimitBytes: 1073741824
    workers: 1
setupImage: registry.redhat.io/openshift4/ose-cli:latest
pullSecret:
  include: true
  secretName: multiclusterhub-operator-pull-secret
  sourceNamespace: openshift-config
  sourceSecretName: pull-secret
objectStorage:
  include: true
  secretName: thanos-object-storage
  key: thanos.yaml
  bucket: observability
  endpoint: s3.openshift-storage.svc
  insecure: false
  accessKey: ""
  secretKey: ""
  httpConfig:
    tlsConfig:
      caFile: /var/run/secrets/kubernetes.io/serviceaccount/service-ca.crt
  objectBucketClaim:
    include: true
    name: observability-obc
    bucketName: observability
    storageClassName: openshift-storage.noobaa.io
observabilityConsoleLink:
  include: false
  name: observability
  href: ""
  location: ApplicationMenu
  section: Red Hat applications
  text: Red Hat Advanced Cluster Management Observability
  imageURL: https://upload.wikimedia.org/wikipedia/commons/3/3a/OpenShift-LogoType.svg
