apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: multi-cluster-config
  namespace: openshift-gitops
spec:
  goTemplate: true
  goTemplateOptions:
    - missingkey=error
  generators:
    - git:
        repoURL: https://github.com/albertogd/gitops-for-organizations.git
        revision: main
        files:
          - path: "clusters/**/conf.yaml"
  template:
    metadata:
      name: '{{.cluster.name}}-operators'
      labels:
        environment: '{{.cluster.environment}}'
        cluster: '{{.cluster.fqdn}}'
    spec:
      project: platform
      source:
        repoURL: https://github.com/albertogd/gitops-for-organizations.git
        targetRevision: main
        path: base/operators
        helm:
          valueFiles:
            - /conf/{{.cluster.environment}}/conf.yaml
            - /clusters/{{.cluster.environment}}/{{.cluster.fqdn}}/conf.yaml
      destination:
        server: '{{.cluster.address}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
          - ApplyOutOfSyncOnly=true
        retry:
          limit: 5
          backoff:
            duration: 30s
            maxDuration: 10m
            factor: 2
  ignoreApplicationDifferences:
    - jsonPointers:
        - /spec/syncPolicy
