{{- $target := index .Values.targets .Values.profile .Values.clusterType }}
{{- range $name := $target.operators }}
{{- $operator := index $.Values.operators $name }}
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: {{ $operator.package }}
  namespace: {{ $operator.namespace }}
  labels:
    operator: {{ $name }}
spec:
  name: {{ $operator.package }}
  channel: {{ index $operator.channelByProfile $.Values.profile }}
  source: {{ $operator.source }}
  sourceNamespace: {{ $operator.sourceNamespace }}
  installPlanApproval: Automatic
---
{{- end }}
