quayNamespace:
  include: false
  name: quay-enterprise
quayRegistry:
  include: false
  name: registry
  namespace: quay-enterprise
  keycloak:
    include: false
    oidcServer: ""
    clientId: "quay"
    clientSecret: ""
