quayNamespace:
  include: false
  name: quay-enterprise
quayRegistry:
  include: false
  name: registry
  namespace: quay-enterprise
  userInitialize: false
  superUsers:
    - quayadmin
  bridge:
    include: false
    quayHostname: ""
    robotAccountToken: ""
  keycloak:
    include: false
    oidcServer: ""
    clientId: "quay"
    clientSecret: ""
