{{- if .Values.quayRegistry.include }}
apiVersion: v1
kind: Secret
metadata:
  name: quay-registry-config-bundle
  namespace: {{ .Values.quayRegistry.namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
type: Opaque
stringData:
  config.yaml: |
    {{- with .Values.quayRegistry.config.serverHostname }}
    SERVER_HOSTNAME: {{ . }}
    PREFERRED_URL_SCHEME: https
    {{- end }}
    SUPER_USERS:
    {{- range .Values.quayRegistry.config.superUsers }}
      - {{ . }}
    {{- end }}
    FEATURE_USER_INITIALIZE: {{ .Values.quayRegistry.config.userInitialize }}
    FEATURE_USER_CREATION: {{ .Values.quayRegistry.config.userCreation }}
    FEATURE_DIRECT_LOGIN: {{ not .Values.quayRegistry.oidc.include }}
    FEATURE_GENERAL_OCI_SUPPORT: {{ .Values.quayRegistry.config.ociSupport }}
    FEATURE_ANONYMOUS_ACCESS: {{ .Values.quayRegistry.config.anonymousAccess }}
    FEATURE_PROXY_STORAGE: {{ .Values.quayRegistry.config.proxyStorage }}
    FEATURE_QUOTA_MANAGEMENT: {{ .Values.quayRegistry.config.quotas.include }}
    FEATURE_AUTO_PRUNE: {{ .Values.quayRegistry.config.autoPrune }}
    FEATURE_GARBAGE_COLLECTION: {{ .Values.quayRegistry.config.garbageCollection }}
    FEATURE_RATE_LIMITS: {{ .Values.quayRegistry.config.rateLimits.include }}
    {{- if .Values.quayRegistry.config.teamSyncing.include }}
    FEATURE_TEAM_SYNCING: true
    FEATURE_NONSUPERUSER_TEAM_SYNCING_SETUP: {{ .Values.quayRegistry.config.teamSyncing.nonSuperuserSetup }}
    TEAM_RESYNC_STALE_TIME: {{ .Values.quayRegistry.config.teamSyncing.resyncStaleTime }}
    {{- else }}
    FEATURE_TEAM_SYNCING: false
    {{- end }}
    {{- if .Values.quayRegistry.config.actionLogRotation.include }}
    FEATURE_ACTION_LOG_ROTATION: true
    ACTION_LOG_ARCHIVE_PATH: {{ .Values.quayRegistry.config.actionLogRotation.archivePath }}
    ACTION_LOG_ARCHIVE_LOCATION: {{ .Values.quayRegistry.config.actionLogRotation.archiveLocation }}
    {{- else }}
    FEATURE_ACTION_LOG_ROTATION: false
    {{- end }}
    {{- if .Values.quayRegistry.components.mirror.managed }}
    FEATURE_REPO_MIRROR: true
    {{- end }}
    DEFAULT_TAG_EXPIRATION: {{ .Values.quayRegistry.config.tagExpiration.default }}
    TAG_EXPIRATION_OPTIONS:
    {{- range .Values.quayRegistry.config.tagExpiration.options }}
      - {{ . }}
    {{- end }}
    ALLOW_PULLS_WITHOUT_STRICT_LOGGING: {{ .Values.quayRegistry.config.allowPullsWithoutStrictLogging }}
    BROWSER_API_CALLS_XHR_ONLY: {{ .Values.quayRegistry.config.browserApiCallsXhrOnly }}
    {{- if .Values.quayRegistry.config.quotas.include }}
    DEFAULT_SYSTEM_REJECT_QUOTA_BYTES: {{ .Values.quayRegistry.config.quotas.defaultSystemRejectBytes | int64 }}
    {{- end }}
    {{- if .Values.quayRegistry.externalDatabase.include }}
    DB_URI: postgresql://{{ .Values.quayRegistry.externalDatabase.username }}:{{ .Values.quayRegistry.externalDatabase.password }}@{{ .Values.quayRegistry.externalDatabase.host }}:{{ .Values.quayRegistry.externalDatabase.port }}/{{ .Values.quayRegistry.externalDatabase.name }}?sslmode={{ .Values.quayRegistry.externalDatabase.sslMode }}
    {{- end }}
    {{- if .Values.quayRegistry.externalStorage.include }}
    DISTRIBUTED_STORAGE_CONFIG:
      {{ .Values.quayRegistry.externalStorage.storageName }}:
        - {{ .Values.quayRegistry.externalStorage.type }}
        -
          {{- toYaml .Values.quayRegistry.externalStorage.config | nindent 10 }}
    DISTRIBUTED_STORAGE_DEFAULT_LOCATIONS:
      - {{ .Values.quayRegistry.externalStorage.storageName }}
    DISTRIBUTED_STORAGE_PREFERENCE:
      - {{ .Values.quayRegistry.externalStorage.storageName }}
    {{- end }}
    {{- if .Values.quayRegistry.oidc.include }}
    {{ upper .Values.quayRegistry.oidc.provider }}_LOGIN_CONFIG:
      CLIENT_ID: {{ .Values.quayRegistry.oidc.clientId }}
      CLIENT_SECRET: {{ .Values.quayRegistry.oidc.clientSecret }}
      OIDC_SERVER: {{ .Values.quayRegistry.oidc.server }}
      SERVICE_NAME: {{ .Values.quayRegistry.oidc.provider }}
      LOGIN_SCOPES:
      {{- range .Values.quayRegistry.oidc.loginScopes }}
        - {{ . }}
      {{- end }}
      VERIFIED_EMAIL_CLAIM_NAME: {{ .Values.quayRegistry.oidc.verifiedEmailClaimName }}
    {{- end }}
  {{- if .Values.quayRegistry.customTls.include }}
  ssl.cert: |
{{ .Values.quayRegistry.customTls.cert | indent 4 }}
  ssl.key: |
{{ .Values.quayRegistry.customTls.key | indent 4 }}
  {{- end }}
{{- end }}
