{{- if and .Values.quayRegistry.include .Values.quayRegistry.bridge.include }}
apiVersion: v1
kind: Secret
metadata:
  name: quay-bridge-token
  namespace: openshift-operators
  annotations:
    argocd.argoproj.io/sync-wave: "1"
type: Opaque
stringData:
  token: {{ required "quay.bridge.oauthToken is required when bridge is enabled" .Values.quayRegistry.bridge.oauthToken }}
---
apiVersion: quay.redhat.com/v1
kind: QuayIntegration
metadata:
  name: quay-bridge
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  clusterID: openshift
  credentialsSecret:
    namespace: openshift-operators
    name: quay-bridge-token
  quayHostname: https://{{ .Values.quayRegistry.bridge.hostname | default (printf "%s-quay-%s.%s" .Values.quayRegistry.name .Values.quayRegistry.namespace .Values.cluster.baseDomain) }}
  insecureRegistry: {{ .Values.quayRegistry.bridge.insecureRegistry }}
  {{- if .Values.quayRegistry.bridge.namespaceCreationDefault }}
  namespaceCreationDefault: true
  {{- end }}
  scheduledImageStreamImport: {{ .Values.quayRegistry.bridge.scheduledImageStreamImport }}
  {{- with .Values.quayRegistry.bridge.denylistNamespaces }}
  denylistNamespaces:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
