multiClusterHub:
  include: false
  name: multiclusterhub
  namespace: open-cluster-management
  availabilityConfig: High
  enableAnalytics: true
  disableHubSelfManagement: false
  clusterInstall: false
  annotations: {}
  overrides:
    components:
      - name: siteconfig
        enabled: true
