apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: cluster-operator-instances
  namespace: openshift-gitops
spec:
  syncPolicy:
    preserveResourcesOnDeletion: true
  goTemplate: true
  goTemplateOptions:
    - missingkey=error
  generators:
    - matrix:
        generators:
          - git:
              repoURL: git@github.com:blediagolli/gitops-for-organizations.git
              revision: main
              files:
                - path: "clusters/**/conf.yaml"
          - list:
              elementsYaml: "{{ .operatorInstanceCharts | toJson }}"
  template:
    metadata:
      name: 'cr-{{.cluster.environment}}-{{.cluster.name}}-{{.chart}}'
      labels:
        environment: '{{.cluster.environment}}'
        cluster: '{{.cluster.name}}'
        type: operator-instances
    spec:
      project: platform
      source:
        repoURL: git@github.com:blediagolli/gitops-for-organizations.git
        targetRevision: main
        path: 'charts/operator-instances/{{.chart}}'
        helm:
          ignoreMissingValueFiles: true
          valueFiles:
            - '/env/{{.cluster.environment}}/conf.yaml'
            - '/env/{{.cluster.environment}}/operator-instances.yaml'
            - '/{{.path.path}}/conf.yaml'
            - '/{{.path.path}}/operator-instances.yaml'
      destination:
        server: '{{.cluster.address}}'
      ignoreDifferences:
        - group: observability.open-cluster-management.io
          kind: MultiClusterObservability
          jsonPointers:
            - /spec/capabilities
      syncPolicy:
        automated:
          selfHeal: true
        retry:
          backoff:
            duration: 30s
            factor: 2
            maxDuration: 10m
          limit: 5
        syncOptions:
          - ApplyOutOfSyncOnly=true
          - RespectIgnoreDifferences=true
