apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: onboarding-gitops
  namespace: openshift-gitops
spec:
  goTemplate: true
  goTemplateOptions:
    - missingkey=error
  generators:
    - git:
        repoURL: git@github.com:blediagolli/gitops-for-organizations.git
        revision: main
        files:
          - path: "clusters/**/teams/*.yaml"
  template:
    metadata:
      name: 'config-{{.cluster.environment}}-{{.cluster.name}}-{{.team.name}}-gitops'
      labels:
        environment: '{{.cluster.environment}}'
        cluster: '{{.cluster.name}}'
        type: onboarding-gitops
    spec:
      project: platform
      source:
        repoURL: git@github.com:blediagolli/gitops-for-organizations.git
        targetRevision: main
        path: charts/onboarding/application-gitops
        helm:
          valueFiles:
            - '/env/{{.cluster.environment}}/conf.yaml'
            - '/{{ trimSuffix "/teams" .path.path }}/conf.yaml'
            - '/{{.path.path}}/{{.path.filename}}'
      destination:
        server: '{{.cluster.address}}'
      syncPolicy:
        automated:
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
        retry:
          limit: 5
          backoff:
            duration: 30s
            maxDuration: 10m
            factor: 2
