apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: cluster-platform-config
  namespace: openshift-gitops
spec:
  goTemplate: true
  goTemplateOptions:
    - missingkey=error
  generators:
    - matrix:
        generators:
          - git:
              repoURL: git@github.com:blediagolli/gitops-for-organizations.git
              revision: main
              files:
                - path: "clusters/**/conf.yaml"
          - list:
              elementsYaml: "{{ .platformCharts | toJson }}"
  template:
    metadata:
      name: 'config-{{.cluster.environment}}-{{.cluster.name}}-{{.chart}}'
      labels:
        environment: '{{.cluster.environment}}'
        cluster: '{{.cluster.name}}'
        type: platform-config
    spec:
      project: platform
      source:
        repoURL: git@github.com:blediagolli/gitops-for-organizations.git
        targetRevision: main
        path: 'charts/platform-config/{{.chart}}'
        helm:
          ignoreMissingValueFiles: true
          valueFiles:
            - '/env/{{.cluster.environment}}/conf.yaml'
            - '/env/{{.cluster.environment}}/platform-config.yaml'
            - '/{{.path.path}}/conf.yaml'
            - '/{{.path.path}}/platform-config.yaml'
      destination:
        server: '{{.cluster.address}}'
      syncPolicy:
        automated:
          selfHeal: true
        retry:
          backoff:
            duration: 30s
            factor: 2
            maxDuration: 10m
          limit: 5
        syncOptions:
          - ApplyOutOfSyncOnly=true
