apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: cluster-provisioning
  namespace: openshift-gitops
spec:
  goTemplate: true
  goTemplateOptions:
    - missingkey=error
  generators:
    - git:
        repoURL: git@github.com:blediagolli/gitops-for-organizations.git
        revision: main
        files:
          - path: "clusters/**/provision.yaml"
  template:
    metadata:
      name: 'provision-{{.cluster.environment}}-{{.cluster.name}}'
      labels:
        environment: '{{.cluster.environment}}'
        cluster: '{{.cluster.name}}'
    spec:
      project: platform
      source:
        repoURL: git@github.com:blediagolli/gitops-for-organizations.git
        targetRevision: main
        path: base/provision/openshift-provisioning
        helm:
          valueFiles:
            - '/{{.path.path}}/provision.yaml'
      destination:
        server: 'https://kubernetes.default.svc'
        namespace:
      syncPolicy:
        syncOptions:
          - preserveResourcesOnDeletion=true
