apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: cluster-config-overlays
  namespace: openshift-gitops
spec:
  goTemplate: true
  goTemplateOptions:
    - missingkey=error
  generators:
    - git:
        repoURL: git@github.com:blediagolli/gitops-for-organizations.git
        revision: main
        files:
          - path: "clusters/**/conf.yaml"
  template:
    metadata:
      name: 'config-{{.cluster.environment}}-{{.cluster.name}}-overlay'
      labels:
        environment: '{{.cluster.environment}}'
        cluster: '{{.cluster.name}}'
        type: config-overlay
    spec:
      project: platform
      source:
        repoURL: git@github.com:blediagolli/gitops-for-organizations.git
        targetRevision: main
        path: '{{.path.path}}/overlay'
      destination:
        server: '{{.cluster.address}}'
      syncPolicy: {}
