apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: cluster-config
  namespace: openshift-gitops
spec:
  goTemplate: true
  goTemplateOptions:
    - missingkey=error
  generators:
    - matrix:
        generators:
          - git:
              repoURL: git@github.com:blediagolli/gitops-for-organizations.git
              revision: main
              files:
                - path: "clusters/**/conf.yaml"
          - list:
              elements:
                - template: openshift-machine-config
                - template: openshift-ingress
                - template: openshift-marketplace
                - template: openshift-dns
                - template: openshift-image-registry
                - template: user-workload-monitoring
                - template: acm-multiclusterhub
                - template: acm-observability
                - template: acs-central
                - template: acs-secured-cluster
                - template: aap-instance
                - template: cert-manager-certs
                - template: compliance-scans
                - template: local-storage-volumes
                - template: logging-lokistack
                - template: lvm-cluster
                - template: metallb-config
                - template: mtv-controller
                - template: nmstate-config
                - template: node-feature-discovery-instance
                - template: odf-storagecluster
                - template: openshift-virtualization-instance
                - template: quay-registry
                - template: servicemesh-ambient
                - template: trident-config
  template:
    metadata:
      name: 'config-{{.cluster.environment}}-{{.cluster.name}}-{{.template}}'
      labels:
        environment: '{{.cluster.environment}}'
        cluster: '{{.cluster.name}}'
    spec:
      project: platform
      source:
        repoURL: git@github.com:blediagolli/gitops-for-organizations.git
        targetRevision: main
        path: 'base/config/{{.template}}'
        helm:
          valueFiles:
            - '/conf/{{.cluster.environment}}/conf.yaml'
            - '/{{.path.path}}/conf.yaml'
      destination:
        server: '{{.cluster.address}}'
      syncPolicy: {}
