apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: cluster-operators
  namespace: openshift-gitops
spec:
  preserveResourcesOnDeletion: true
  goTemplate: true
  goTemplateOptions:
    - missingkey=error
  generators:
    - matrix:
        generators:
          - git:
              repoURL: git@github.com:blediagolli/gitops-for-organizations.git
              revision: main
              files:
                - path: "clusters/**/conf.yaml"
          - list:
              elementsYaml: "{{ $d := index . \"deployOperators\" }}{{ if $d }}[{}]{{ else }}[]{{ end }}"
  template:
    metadata:
      name: 'operators-{{.cluster.environment}}-{{.cluster.name}}'
      labels:
        environment: '{{.cluster.environment}}'
        cluster: '{{.cluster.name}}'
        type: operators
    spec:
      project: platform
      source:
        repoURL: git@github.com:blediagolli/gitops-for-organizations.git
        targetRevision: main
        path: charts/operator-deployment
        helm:
          ignoreMissingValueFiles: true
          valueFiles:
            - '/env/{{.cluster.environment}}/conf.yaml'
            - '/env/{{.cluster.environment}}/operator-deployment.yaml'
            - '/{{.path.path}}/conf.yaml'
            - '/{{.path.path}}/operator-deployment.yaml'
      destination:
        server: '{{.cluster.address}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
          - ApplyOutOfSyncOnly=true
        retry:
          limit: 5
          backoff:
            duration: 30s
            maxDuration: 10m
            factor: 2
  ignoreApplicationDifferences:
    - jsonPointers:
        - /spec/syncPolicy
