apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: onboarding-gitops
  namespace: openshift-gitops
spec:
  syncPolicy:
    preserveResourcesOnDeletion: true
  goTemplate: true
  goTemplateOptions:
    - missingkey=error
  generators:
    - matrix:
        generators:
          - git:
              repoURL: git@github.com:blediagolli/gitops-for-organizations.git
              revision: main
              files:
                - path: "clusters/**/conf.yaml"
          - list:
              elementsYaml: "{{ .teams | toJson }}"
  template:
    metadata:
      name: 'onboarding-gitops-{{.cluster.environment}}-{{.cluster.name}}-{{.team}}'
      labels:
        environment: '{{.cluster.environment}}'
        cluster: '{{.cluster.name}}'
        type: onboarding-gitops
    spec:
      project: platform
      source:
        repoURL: git@github.com:blediagolli/gitops-for-organizations.git
        targetRevision: main
        path: charts/onboarding/application-gitops
        helm:
          ignoreMissingValueFiles: true
          valueFiles:
            - '/teams/{{.team}}.yaml'
            - '/env/{{.cluster.environment}}/conf.yaml'
            - '/env/{{.cluster.environment}}/teams/{{.team}}.yaml'
            - '/{{.path.path}}/conf.yaml'
            - '/{{.path.path}}/teams/{{.team}}.yaml'
      destination:
        server: '{{ or .cluster.address (printf "https://cluster-proxy-addon-user.multicluster-engine.svc.cluster.local:9092/%s" .cluster.name) }}'
      syncPolicy:
        automated:
          selfHeal: true
          prune: true
        syncOptions:
          - CreateNamespace=true
        retry:
          limit: 5
          backoff:
            duration: 30s
            maxDuration: 10m
            factor: 2
