apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- cluster-platform-config.yaml
- cluster-operator-instances.yaml
- cluster-config-overlays.yaml
- cluster-import.yaml
- cluster-operators-appset.yaml
- cluster-provisioning.yaml
- cluster-onboarding-gitops.yaml
- cluster-onboarding-namespaces.yaml
