managedCluster:
  include: false
  registerArgoCD: false
  vendor: OpenShift
  cloudProvider: auto-detect
  clusterSet: default
  labels: {}
  hubAcceptsClient: true

  autoImport:
    include: false
    mode: kubeconfig
    kubeconfig:
      secretName: ""
    token:
      server: ""
      value: ""

  addons:
    include: true
    configPolicyController: true
    governancePolicyFramework: true
    workManager: true
    applicationManager: true
    certPolicyController: true
    policyController: true
    searchCollector: true
    clusterProxy: false
    managedServiceAccount: false
