{{- if .Values.secretStore.include }}
apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: {{ .Values.secretStore.name }}
spec:
  provider:
    vault:
      server: {{ include "vault-server.address" . }}
      path: {{ .Values.secretStore.path }}
      version: "v{{ .Values.secretStore.kvVersion }}"
      auth:
        kubernetes:
          mountPath: {{ .Values.vault.kubernetesAuth.path }}
          role: {{ .Values.secretStore.auth.role }}
          serviceAccountRef:
            name: {{ .Values.secretStore.auth.serviceAccountRef.name }}
            namespace: {{ .Values.secretStore.auth.serviceAccountRef.namespace }}
{{- end }}
