{{- if .Values.vault.include }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: vault-config
  namespace: {{ .Values.vault.namespace }}
  labels:
    app.kubernetes.io/name: vault
    app.kubernetes.io/instance: vault
data:
  vault.hcl: |
    ui = true
    disable_mlock = true

    listener "tcp" {
      address         = "0.0.0.0:8200"
      cluster_address = "0.0.0.0:8201"
      tls_disable     = 1
    }

    storage "raft" {
      path = "/vault/data"
      {{- range $i := until (int .Values.vault.replicas) }}
      retry_join {
        leader_api_addr = "http://vault-{{ $i }}.vault-internal.{{ $.Values.vault.namespace }}.svc:8200"
      }
      {{- end }}
    }

    service_registration "kubernetes" {}

    {{- if .Values.vault.audit.enabled }}

    telemetry {
      disable_hostname = true
      prometheus_retention_time = "12h"
    }
    {{- end }}
{{- end }}
