{{- if .Values.vault.include }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.vault.serviceAccount.name }}
  namespace: {{ .Values.vault.namespace }}
  labels:
    app.kubernetes.io/name: vault
    app.kubernetes.io/instance: vault
---
{{- if .Values.vault.kubernetesAuth.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.secretStore.auth.serviceAccountRef.name }}
  namespace: {{ .Values.vault.namespace }}
  labels:
    app.kubernetes.io/name: vault
    app.kubernetes.io/component: external-secrets
{{- end }}
{{- end }}
