{{- if .Values.vault.include }}
apiVersion: v1
kind: Service
metadata:
  name: vault
  namespace: {{ .Values.vault.namespace }}
  labels:
    app.kubernetes.io/name: vault
    app.kubernetes.io/instance: vault
spec:
  publishNotReadyAddresses: true
  ports:
    - name: http
      port: 8200
      targetPort: 8200
    - name: https-internal
      port: 8201
      targetPort: 8201
  selector:
    app.kubernetes.io/name: vault
    app.kubernetes.io/instance: vault
---
apiVersion: v1
kind: Service
metadata:
  name: vault-active
  namespace: {{ .Values.vault.namespace }}
  labels:
    app.kubernetes.io/name: vault
    app.kubernetes.io/instance: vault
spec:
  publishNotReadyAddresses: true
  ports:
    - name: http
      port: 8200
      targetPort: 8200
    - name: https-internal
      port: 8201
      targetPort: 8201
  selector:
    app.kubernetes.io/name: vault
    app.kubernetes.io/instance: vault
    vault-active: "true"
---
apiVersion: v1
kind: Service
metadata:
  name: vault-internal
  namespace: {{ .Values.vault.namespace }}
  labels:
    app.kubernetes.io/name: vault
    app.kubernetes.io/instance: vault
spec:
  clusterIP: None
  publishNotReadyAddresses: true
  ports:
    - name: http
      port: 8200
      targetPort: 8200
    - name: https-internal
      port: 8201
      targetPort: 8201
  selector:
    app.kubernetes.io/name: vault
    app.kubernetes.io/instance: vault
{{- end }}
