{{- if .Values.provision.include }}
apiVersion: hive.openshift.io/v1
kind: ClusterDeployment
metadata:
  name: {{ .Values.cluster.name }}
  namespace: {{ .Values.cluster.name }}
  annotations:
    helm.sh/hook-weight: "357"
  labels:
    cloud: {{ include "cluster.cloudLabel" . }}
    vendor: OpenShift
    hive.openshift.io/cluster-platform: {{ .Values.cluster.platform }}
    cluster.open-cluster-management.io/clusterset: {{ .Values.cluster.clusterSet }}
spec:
  baseDomain: {{ .Values.cluster.baseDomain }}
  clusterName: {{ .Values.cluster.name }}
  controlPlaneConfig:
    servingCertificates: {}
  {{- if eq (include "cluster.isAgent" .) "true" }}
  installed: false
  {{- else }}
  installAttemptsLimit: 1
  {{- end }}
  {{- if eq .Values.cluster.platform "vsphere" }}
  platform:
    vsphere:
      cluster: {{ .Values.vsphere.cluster }}
      certificatesSecretRef:
        name: {{ .Values.cluster.name }}-vsphere-certs
      credentialsSecretRef:
        name: {{ .Values.cluster.name }}-vsphere-creds
      vCenter: {{ .Values.vsphere.vcenter }}
      datacenter: {{ .Values.vsphere.datacenter }}
      defaultDatastore: {{ .Values.vsphere.datastore }}
      network: {{ .Values.vsphere.network }}
  {{- else if eq .Values.cluster.platform "aws" }}
  platform:
    aws:
      credentialsSecretRef:
        name: {{ .Values.cluster.name }}-aws-creds
      region: {{ .Values.aws.region }}
  {{- else }}
  platform:
    agentBareMetal:
      agentSelector:
        matchLabels:
          cluster-name: {{ .Values.cluster.name }}
  clusterInstallRef:
    group: extensions.hive.openshift.io
    kind: AgentClusterInstall
    name: {{ .Values.cluster.name }}
    version: v1beta1
  {{- end }}
  {{- if eq (include "cluster.isIPI" .) "true" }}
  provisioning:
    installConfigSecretRef:
      name: {{ .Values.cluster.name }}-install-config
    sshPrivateKeySecretRef:
      name: {{ .Values.cluster.name }}-ssh-private-key
    imageSetRef:
      name: {{ .Values.cluster.imageSetRef }}
    {{- if or .Values.imageContentSources.enabled .Values.customManifests.enabled }}
    manifestsConfigMapRef:
      {{- if .Values.customManifests.enabled }}
      name: {{ .Values.cluster.name }}-custom-manifests
      {{- else }}
      name: {{ .Values.cluster.name }}-image-content-sources
      {{- end }}
    {{- end }}
  {{- end }}
  pullSecretRef:
    name: {{ .Values.cluster.name }}-pull-secret
{{- end }}
