{{- if and .Values.provision.include (eq (include "cluster.isAgent" .) "true") .Values.vsphereControlPlane.enabled .Values.vsphereControlPlane.simulator.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.cluster.name }}-vcsim
  namespace: {{ .Values.cluster.name }}
  annotations:
    argocd.argoproj.io/sync-wave: "7"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.cluster.name }}-vcsim
  template:
    metadata:
      labels:
        app: {{ .Values.cluster.name }}-vcsim
    spec:
      containers:
        - name: vcsim
          image: {{ .Values.vsphereControlPlane.simulator.image }}
          args: ["-l", ":8443"]
          ports:
            - containerPort: 8443
          volumeMounts:
            - name: tmp
              mountPath: /tmp
      volumes:
        - name: tmp
          emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.cluster.name }}-vcsim
  namespace: {{ .Values.cluster.name }}
  annotations:
    argocd.argoproj.io/sync-wave: "7"
spec:
  selector:
    app: {{ .Values.cluster.name }}-vcsim
  ports:
    - port: 443
      targetPort: 8443
{{- end }}
