{{- if and .Values.provision.include (eq (include "cluster.isIPI" .) "true") }}
apiVersion: hive.openshift.io/v1
kind: MachinePool
metadata:
  name: {{ .Values.cluster.name }}-worker
  namespace: {{ .Values.cluster.name }}
  annotations:
    helm.sh/hook-weight: "360"
spec:
  clusterDeploymentRef:
    name: {{ .Values.cluster.name }}
  name: worker
  replicas: {{ .Values.workers.count }}
  platform:
    {{- if eq .Values.cluster.platform "vsphere" }}
    vsphere:
      cpus: {{ .Values.vsphere.workers.cpus }}
      coresPerSocket: {{ .Values.vsphere.workers.coresPerSocket }}
      memoryMB: {{ .Values.vsphere.workers.memoryMB }}
      osDisk:
        diskSizeGB: {{ .Values.vsphere.workers.diskGB }}
    {{- else if eq .Values.cluster.platform "aws" }}
    aws:
      rootVolume:
        iops: 100
        size: {{ .Values.aws.workers.rootVolume.size }}
        type: {{ .Values.aws.workers.rootVolume.type }}
      type: {{ .Values.aws.workers.instanceType }}
      {{- if .Values.aws.workers.zones }}
      zones:
        {{- toYaml .Values.aws.workers.zones | nindent 8 }}
      {{- end }}
    {{- end }}
{{- end }}
