{{- if and .Values.provision.include (eq (include "cluster.isAgent" .) "true") }}
{{- $platformCfg := index .Values .Values.cluster.platform }}
{{- range $platformCfg.hosts }}
{{- if .nmstate }}
---
apiVersion: agent-install.openshift.io/v1beta1
kind: NMStateConfig
metadata:
  name: {{ .name }}
  namespace: {{ $.Values.cluster.name }}
  annotations:
    helm.sh/hook-weight: "361"
  labels:
    cluster-name: {{ $.Values.cluster.name }}
spec:
  config:
    {{- toYaml .nmstate.config | nindent 4 }}
  interfaces:
    {{- toYaml .nmstate.interfaces | nindent 4 }}
{{- end }}
{{- end }}
{{- end }}
