{{- if and .Values.provision.include (eq (include "cluster.isAgent" .) "true") .Values.vsphereControlPlane.enabled (eq (include "cluster.useExternalSecret" (dict "root" . "key" "vsphereControlPlaneCreds")) "false") }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.cluster.name }}-vsphere-cp-creds
  namespace: {{ .Values.cluster.name }}
  annotations:
    argocd.argoproj.io/sync-wave: "6"
type: Opaque
stringData:
  username: {{ .Values.vsphereControlPlane.username }}
  password: {{ .Values.vsphereControlPlane.password }}
{{- end }}
