{{- if and .Values.provision.include (eq (include "cluster.isAgent" .) "true") }}
{{- $platformCfg := index .Values .Values.cluster.platform }}
{{- $defaultBmc := $platformCfg.bmc | default dict }}
{{- $useES := eq (include "cluster.useExternalSecret" (dict "root" $ "key" "bmcCreds")) "true" }}
{{- range $platformCfg.hosts }}
{{- $hasOverride := and .bmcUsername .bmcPassword }}
{{- if or (not $useES) $hasOverride }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .name }}-bmc-credentials
  namespace: {{ $.Values.cluster.name }}
  annotations:
    argocd.argoproj.io/sync-wave: "6"
type: Opaque
stringData:
  username: {{ .bmcUsername | default ($defaultBmc.username | default "") }}
  password: {{ .bmcPassword | default ($defaultBmc.password | default "") }}
{{- end }}
{{- end }}
{{- end }}
