{{- if and .Values.provision.include (eq .Values.cluster.platform "vsphere") (eq (include "cluster.useExternalSecret" (dict "root" . "key" "vsphereCerts")) "false") }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.cluster.name }}-vsphere-certs
  namespace: {{ .Values.cluster.name }}
  annotations:
    argocd.argoproj.io/sync-wave: "1"
type: Opaque
stringData:
  .cacert: {{- .Values.vsphere.cacertificate | toYaml | indent 2 }}
{{- end }}
