{{- if and .Values.provision.include (eq (include "cluster.isIPI" .) "true") }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.cluster.name }}-ssh-private-key
  namespace: {{ .Values.cluster.name }}
  annotations:
    helm.sh/hook-weight: "355"
type: Opaque
stringData:
  ssh-privatekey: {{- .Values.cluster.sshPrivateKey | toYaml | indent 2 }}
{{- end }}
