{{- if and .Values.provision.include (eq (include "cluster.isIPI" .) "true") }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.cluster.name }}-install-config
  namespace: {{ .Values.cluster.name }}
  annotations:
    helm.sh/hook-weight: "355"
stringData:
  install-config.yaml: |-
    apiVersion: v1
    metadata:
      name: {{ .Values.cluster.name }}
    baseDomain: {{ .Values.cluster.baseDomain }}
    networking:
      networkType: {{ .Values.cluster.networkType }}
    controlPlane:
      hyperthreading: Enabled
      name: master
      replicas: {{ .Values.masters.count }}
      {{- if eq .Values.cluster.platform "vsphere" }}
      platform:
        vsphere:
          cpus: {{ .Values.vsphere.masters.cpus }}
          coresPerSocket: {{ .Values.vsphere.masters.coresPerSocket }}
          memoryMB: {{ .Values.vsphere.masters.memoryMB }}
          osDisk:
            diskSizeGB: {{ .Values.vsphere.masters.diskGB }}
      {{- else if eq .Values.cluster.platform "aws" }}
      platform:
        aws:
          type: {{ .Values.aws.masters.instanceType }}
          {{- if .Values.aws.masters.zones }}
          zones:
            {{- toYaml .Values.aws.masters.zones | nindent 12 }}
          {{- end }}
          rootVolume:
            size: {{ .Values.aws.masters.rootVolume.size }}
            type: {{ .Values.aws.masters.rootVolume.type }}
      {{- end }}
    compute:
      - hyperthreading: Enabled
        name: worker
        replicas: {{ .Values.workers.count }}
        {{- if eq .Values.cluster.platform "vsphere" }}
        platform:
          vsphere:
            cpus: {{ .Values.vsphere.workers.cpus }}
            coresPerSocket: {{ .Values.vsphere.workers.coresPerSocket }}
            memoryMB: {{ .Values.vsphere.workers.memoryMB }}
            osDisk:
              diskSizeGB: {{ .Values.vsphere.workers.diskGB }}
        {{- else if eq .Values.cluster.platform "aws" }}
        platform:
          aws:
            type: {{ .Values.aws.workers.instanceType }}
            {{- if .Values.aws.workers.zones }}
            zones:
              {{- toYaml .Values.aws.workers.zones | nindent 14 }}
            {{- end }}
            rootVolume:
              size: {{ .Values.aws.workers.rootVolume.size }}
              type: {{ .Values.aws.workers.rootVolume.type }}
        {{- end }}
    {{- if eq .Values.cluster.platform "vsphere" }}
    platform:
      vsphere:
        vCenter: {{ .Values.vsphere.vcenter }}
        username: {{ .Values.vsphere.username }}
        password: {{ .Values.vsphere.password }}
        datacenter: {{ .Values.vsphere.datacenter }}
        defaultDatastore: {{ .Values.vsphere.datastore }}
        cluster: {{ .Values.vsphere.cluster }}
        folder: {{ .Values.vsphere.folder }}
        apiVIP: {{ .Values.vsphere.apiVIP }}
        ingressVIP: {{ .Values.vsphere.ingressVIP }}
        network: {{ .Values.vsphere.network }}
    {{- else if eq .Values.cluster.platform "aws" }}
    platform:
      aws:
        region: {{ .Values.aws.region }}
    {{- end }}
    {{- if .Values.cluster.fips }}
    fips: true
    {{- end }}
    {{- if .Values.proxy.enabled }}
    proxy:
      httpProxy: {{ .Values.proxy.httpProxy | quote }}
      httpsProxy: {{ .Values.proxy.httpsProxy | quote }}
      noProxy: {{ .Values.proxy.noProxy | quote }}
    {{- end }}
    pullSecret: ""
    {{- if .Values.imageContentSources.enabled }}
    imageContentSources:
      - mirrors:
          - {{ .Values.imageContentSources.mirror }}
        source: quay.io/openshift-release-dev/ocp-release
      - mirrors:
          - {{ .Values.imageContentSources.mirror }}
        source: quay.io/openshift-release-dev/ocp-v4.0-art-dev
    {{- end }}
    sshKey: {{ .Values.cluster.sshPublicKey }}
    {{- if .Values.cluster.additionalTrustBundle }}
    additionalTrustBundle: {{ .Values.cluster.additionalTrustBundle | toYaml | indent 4 }}
    {{- end }}
{{- end }}
