{{- if and .Values.provision.include (or .Values.cluster.pullSecret .Values.imageContentSources.enabled) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.cluster.name }}-pull-secret
  namespace: {{ .Values.cluster.name }}
  annotations:
    argocd.argoproj.io/sync-wave: "1"
{{- if .Values.imageContentSources.enabled }}
data:
  .dockerconfigjson: {{ template "imagePullSecret" . }}
{{- else }}
stringData:
  .dockerconfigjson: {{ .Values.cluster.pullSecret | quote }}
{{- end }}
type: kubernetes.io/dockerconfigjson
{{- end }}
