{{- if and .Values.provision.include (eq (include "cluster.isAgent" .) "true") }}
{{- $platformCfg := index .Values .Values.cluster.platform }}
{{- $defaultBmc := $platformCfg.bmc | default dict }}
{{- range $platformCfg.hosts }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .name }}-bmc-credentials
  namespace: {{ $.Values.cluster.name }}
  annotations:
    helm.sh/hook-weight: "355"
type: Opaque
stringData:
  username: {{ .bmcUsername | default ($defaultBmc.username | default "") }}
  password: {{ .bmcPassword | default ($defaultBmc.password | default "") }}
{{- end }}
{{- end }}
