{{- if .Values.provision.include }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.cluster.name }}-pull-secret
  namespace: {{ .Values.cluster.name }}
  annotations:
    helm.sh/hook-weight: "355"
{{- if .Values.imageContentSources.enabled }}
data:
  .dockerconfigjson: {{ template "imagePullSecret" . }}
{{- else }}
stringData:
  .dockerconfigjson: {{ .Values.cluster.pullSecret | quote }}
{{- end }}
type: kubernetes.io/dockerconfigjson
{{- end }}
