keycloak:
  include: false
  createNamespace: false
  name: keycloak
  namespace: keycloak
  instances: 1
  hostname: ""
  db:
    vendor: postgres
    host: ""
    database: keycloak
    usernameSecret:
      name: ""
      key: username
    passwordSecret:
      name: ""
      key: password

realm:
  include: false
  name: sso
  groups: []
  users: []
  clients:
    quay:
      include: false
      clientId: quay
      clientSecret: ""
      publicClient: false
      standardFlowEnabled: true
      directAccessGrantsEnabled: false
      redirectUris: []
      webOrigins: []
    openshift:
      include: false
      clientId: openshift
      clientSecret: ""
      publicClient: false
      standardFlowEnabled: true
      directAccessGrantsEnabled: false
      redirectUris: []
      webOrigins: []
      defaultClientScopes:
        - web-origins
        - acr
        - profile
        - email
      protocolMappers:
        - name: groups
          protocol: openid-connect
          protocolMapper: oidc-group-membership-mapper
          config:
            claim.name: groups
            full.path: "false"
            id.token.claim: "true"
            access.token.claim: "true"
            userinfo.token.claim: "true"
    stackrox:
      include: false
      clientId: stackrox
      clientSecret: ""
      publicClient: false
      standardFlowEnabled: true
      directAccessGrantsEnabled: false
      serviceAccountsEnabled: true
      redirectUris: []
      webOrigins: []
      defaultClientScopes:
        - web-origins
        - acr
        - profile
        - email
      optionalClientScopes:
        - offline_access
        - address
        - phone
        - microprofile-jwt
      protocolMappers:
        - name: groups
          protocol: openid-connect
          protocolMapper: oidc-group-membership-mapper
          config:
            claim.name: groups
            full.path: "false"
            id.token.claim: "true"
            access.token.claim: "true"
            userinfo.token.claim: "true"
