{{- if .Values.multiClusterObservability.include }}
apiVersion: observability.open-cluster-management.io/v1beta2
kind: MultiClusterObservability
metadata:
  name: {{ .Values.multiClusterObservability.name }}
spec:
  {{- if .Values.multiClusterObservability.capabilities }}
  capabilities:
    {{- toYaml .Values.multiClusterObservability.capabilities | nindent 4 }}
  {{- end }}
  observabilityAddonSpec:
    enableMetrics: true
    {{- with .Values.multiClusterObservability.observabilityAddonSpec }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  retentionConfig:
    retentionResolutionRaw: {{ .Values.multiClusterObservability.retention.raw }}
    retentionResolution5m: {{ .Values.multiClusterObservability.retention.fiveMinute }}
    retentionResolution1h: {{ .Values.multiClusterObservability.retention.oneHour }}
    blockDuration: {{ .Values.multiClusterObservability.retention.blockDuration }}
    deleteDelay: {{ .Values.multiClusterObservability.retention.deleteDelay }}
  storageConfig:
    metricObjectStorage:
      name: {{ .Values.objectStorage.secretName }}
      key: {{ .Values.objectStorage.key }}
    storageClass: {{ .Values.multiClusterObservability.storageClass }}
    compactStorageSize: {{ .Values.multiClusterObservability.compactStorageSize }}
    receiveStorageSize: {{ .Values.multiClusterObservability.receiveStorageSize }}
    ruleStorageSize: {{ .Values.multiClusterObservability.ruleStorageSize }}
    storeStorageSize: {{ .Values.multiClusterObservability.storeStorageSize }}
{{- end }}
