{{- if and .Values.pullSecret.include .Values.multiClusterObservability.include }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.pullSecret.secretName }}
  namespace: {{ .Values.multiClusterObservability.namespace }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ printf "%s" "{{ fromSecret \"%s\" \"%s\" \".dockerconfigjson\" }}" .Values.pullSecret.sourceNamespace .Values.pullSecret.sourceSecretName | quote }}
{{- end }}
