{{- if and .Values.objectStorage.include .Values.multiClusterObservability.include }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.objectStorage.secretName }}
  namespace: {{ .Values.multiClusterObservability.namespace }}
type: Opaque
stringData:
  thanos.yaml: |
    type: s3
    config:
      bucket: {{ .Values.objectStorage.bucket }}
      endpoint: '{{ .Values.objectStorage.endpoint }}'
      insecure: {{ .Values.objectStorage.insecure | toString | lower }}
      access_key: {{ .Values.objectStorage.accessKey }}
      secret_key: {{ .Values.objectStorage.secretKey }}
      http_config:
        tls_config:
          ca_file: {{ .Values.objectStorage.httpConfig.tlsConfig.caFile }}
{{- end }}
