{{- $v := index .Values .Chart.Name }}
{{- if $v.uiPlugins.distributedTracing.include }}
apiVersion: observability.openshift.io/v1alpha1
kind: UIPlugin
metadata:
  name: distributed-tracing
spec:
  type: DistributedTracing
  {{- with $v.uiPlugins.distributedTracing.timeout }}
  distributedTracing:
    timeout: {{ . }}
  {{- end }}
{{- end }}
