{{- if .Values.lokiStack.include }}
apiVersion: loki.grafana.com/v1
kind: LokiStack
metadata:
  name: {{ .Values.lokiStack.name }}
  namespace: {{ .Values.lokiStack.namespace }}
  annotations:
    lokistack.openshift.io/storage-size: {{ .Values.lokiStack.storageSize | quote }}
spec:
  size: {{ .Values.lokiStack.size }}
  storage:
    schemas:
      - version: v13
        effectiveDate: "2024-09-22"
    secret:
      name: {{ .Values.lokiStack.secretName }}
      type: {{ .Values.lokiStack.storageSecretType }}
  storageClassName: {{ .Values.lokiStack.storageClassName }}
  tenants:
    mode: openshift-logging
  hashRing:
    type: memberlist
  limits:
    global:
      ingestion:
        ingestionRate: {{ .Values.lokiStack.ingestionRate }}
        ingestionBurstSize: {{ .Values.lokiStack.ingestionBurstSize }}
      queries:
        queryTimeout: {{ .Values.lokiStack.queryTimeout }}
{{- end }}
