{{- if .Values.lokiStack.include }}
apiVersion: loki.grafana.com/v1
kind: LokiStack
metadata:
  name: {{ .Values.lokiStack.name }}
  namespace: {{ .Values.lokiStack.namespace }}
spec:
  size: {{ .Values.lokiStack.size }}
  storage:
    schemas:
      - version: v13
        effectiveDate: "2024-09-22"
    secret:
      name: {{ .Values.lokiStack.secretName }}
      type: s3
  storageClassName: {{ .Values.lokiStack.storageClassName }}
  tenants:
    mode: openshift-logging
  hashRing:
    type: memberlist
  limits:
    global:
      ingestion:
        ingestionRate: 8
        ingestionBurstSize: 16
      queries:
        queryTimeout: 3m
{{- end }}
