securedCluster:
  include: false
  name: stackrox-secured-cluster-services
  namespace: stackrox
  clusterName: ""
  centralEndpoint: ""
  admissionControl:
    listenOnCreates: true
    listenOnUpdates: true
    listenOnEvents: true
    contactImageScanners: ScanIfMissing
  collector:
    collection: CORE_BPF
    imageFlavor: Regular
  taintToleration: TolerateTaints
securedClusterNamespace:
  include: false
