{{- range $name, $operator := .Values.operators }}
{{- if $operator.include }}
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: {{ $operator.package }}
  namespace: {{ $operator.namespace }}
  labels:
    operator: {{ $name }}
spec:
  name: {{ $operator.package }}
  channel: {{ $operator.channel }}
  source: {{ $operator.source }}
  sourceNamespace: {{ $operator.sourceNamespace }}
  installPlanApproval: Automatic
---
{{- end }}
{{- end }}
