apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

patches:
  - target:
      group: operators.coreos.com
      version: v1alpha1
      kind: Subscription
      name: openshift-gitops-operator
    patch: |-
      - op: replace
        path: /spec/channel
        value: gitops-1.20
  - target:
      group: operators.coreos.com
      version: v1alpha1
      kind: Subscription
      name: advanced-cluster-management
    patch: |-
      - op: replace
        path: /spec/channel
        value: release-2.16
  - target:
      group: operators.coreos.com
      version: v1alpha1
      kind: Subscription
      name: odf-operator
    patch: |-
      - op: replace
        path: /spec/channel
        value: stable-4.21
  - target:
      group: operators.coreos.com
      version: v1alpha1
      kind: Subscription
      name: cluster-logging
    patch: |-
      - op: replace
        path: /spec/channel
        value: stable-6.5
