{{- if and .Values.ingress.controller.include .Values.ingress.controller.manageDefault }}
apiVersion: operator.openshift.io/v1
kind: IngressController
metadata:
  name: default
  namespace: openshift-ingress-operator
  {{- if .Values.ingress.controller.http2.enabled }}
  annotations:
    ingress.operator.openshift.io/default-enable-http2: "true"
  {{- end }}
spec:
  endpointPublishingStrategy:
    type: {{ .Values.ingress.controller.default.endpointPublishingStrategy }}

  nodePlacement:
    nodeSelector:
      matchLabels:
        {{ .Values.ingress.controller.default.placement }}: ""
    {{- if .Values.ingress.controller.default.tolerations }}
    tolerations:
      {{- toYaml .Values.ingress.controller.default.tolerations | nindent 6 }}
    {{- end }}

  replicas: {{ .Values.ingress.controller.default.replicas }}

  {{- if .Values.ingress.controller.defaultCertificate.enabled }}
  defaultCertificate:
    name: {{ .Values.ingress.controller.defaultCertificate.name }}
  {{- end }}

  {{- if .Values.ingress.controller.tlsSecurityProfile.enabled }}
  tlsSecurityProfile:
    type: {{ .Values.ingress.controller.tlsSecurityProfile.type }}
    {{- if eq .Values.ingress.controller.tlsSecurityProfile.type "Custom" }}
    custom:
      ciphers:
        {{- toYaml .Values.ingress.controller.tlsSecurityProfile.custom.ciphers | nindent 8 }}
      minTLSVersion: {{ .Values.ingress.controller.tlsSecurityProfile.custom.minTLSVersion }}
    {{- end }}
  {{- end }}

  {{- if .Values.ingress.controller.hsts.enabled }}
  httpHeaders:
    actions:
      response:
        - name: Strict-Transport-Security
          action:
            type: Set
            set:
              value: {{ .Values.ingress.controller.hsts.value | quote }}
  {{- end }}

  {{- if .Values.ingress.controller.logging.enabled }}
  logging:
    access:
      destination:
        {{- if eq .Values.ingress.controller.logging.destination.type "Syslog" }}
        syslog:
          address: {{ .Values.ingress.controller.logging.destination.syslog.address }}
          port: {{ .Values.ingress.controller.logging.destination.syslog.port }}
        {{- end }}
        type: {{ .Values.ingress.controller.logging.destination.type }}
  {{- end }}
{{- end }}
