operators:
  openshift-gitops:
    include: false
    namespace: openshift-gitops-operator
    operatorGroup: openshift-gitops-operator
    package: openshift-gitops-operator
    channel: gitops-1.21
    source: redhat-operators
    sourceNamespace: openshift-marketplace
    clusterScoped: true
  advanced-cluster-management:
    include: false
    namespace: open-cluster-management
    operatorGroup: open-cluster-management
    package: advanced-cluster-management
    channel: release-2.17
    source: redhat-operators
    sourceNamespace: openshift-marketplace
    namespaceAnnotations:
      openshift.io/node-selector: ""
    namespaceLabels:
      openshift.io/cluster-monitoring: "true"
  advanced-cluster-security:
    include: false
    namespace: rhacs-operator
    operatorGroup: rhacs-operator
    package: rhacs-operator
    channel: stable
    source: redhat-operators
    sourceNamespace: openshift-marketplace
    clusterScoped: true
  ansible-automation-platform:
    include: false
    namespace: ansible-automation-platform
    operatorGroup: ansible-automation-platform
    package: ansible-automation-platform-operator
    channel: stable-2.4
    source: redhat-operators
    sourceNamespace: openshift-marketplace
  cert-manager:
    include: false
    namespace: cert-manager-operator
    operatorGroup: cert-manager-operator
    package: openshift-cert-manager-operator
    channel: change-me
    source: redhat-operators
    sourceNamespace: openshift-marketplace
    clusterScoped: true
  cloudnative-pg:
    include: false
    namespace: openshift-operators
    package: cloudnative-pg
    channel: change-me
    source: certified-operators
    sourceNamespace: openshift-marketplace
    skipNamespace: true
    skipOperatorGroup: true
  cluster-observability:
    include: false
    namespace: openshift-operators
    package: cluster-observability-operator
    channel: change-me
    source: redhat-operators
    sourceNamespace: openshift-marketplace
    skipNamespace: true
    skipOperatorGroup: true
  compliance-operator:
    include: false
    namespace: openshift-compliance
    operatorGroup: openshift-compliance
    package: compliance-operator
    channel: release-0.1
    source: redhat-operators
    sourceNamespace: openshift-marketplace
  dev-spaces:
    include: false
    namespace: openshift-operators-redhat
    package: devspaces
    channel: change-me
    source: redhat-operators
    sourceNamespace: openshift-marketplace
    skipNamespace: true
    skipOperatorGroup: true
  developer-hub:
    include: false
    namespace: rhdh-operator
    operatorGroup: rhdh-operator
    package: rhdh
    channel: change-me
    source: redhat-operators
    sourceNamespace: openshift-marketplace
    clusterScoped: true
  external-secrets-operator:
    include: false
    namespace: external-secrets-operator
    operatorGroup: external-secrets-operator
    package: openshift-external-secrets-operator
    channel: change-me
    source: redhat-operators
    sourceNamespace: openshift-marketplace
    clusterScoped: true
  gitlab:
    include: false
    namespace: gitlab-system
    operatorGroup: gitlab-system
    package: gitlab-operator-kubernetes
    channel: change-me
    source: certified-operators
    sourceNamespace: openshift-marketplace
  gitlab-runner:
    include: false
    namespace: gitlab-runner-system
    operatorGroup: gitlab-runner-system
    package: gitlab-runner-operator
    channel: change-me
    source: redhat-operators
    sourceNamespace: openshift-marketplace
  jfrog:
    include: false
    namespace: jfrog-system
    operatorGroup: jfrog-system
    package: openshiftartifactoryha-operator
    channel: change-me
    source: certified-operators
    sourceNamespace: openshift-marketplace
  kiali:
    include: false
    namespace: openshift-operators
    package: kiali-ossm
    channel: change-me
    source: redhat-operators
    sourceNamespace: openshift-marketplace
    skipNamespace: true
    skipOperatorGroup: true
  openshift-local-storage:
    include: false
    namespace: openshift-local-storage
    operatorGroup: openshift-local-storage
    package: local-storage-operator
    channel: stable
    source: redhat-operators
    sourceNamespace: openshift-marketplace
  openshift-logging:
    include: false
    namespace: openshift-logging
    operatorGroup: openshift-logging
    package: cluster-logging
    channel: change-me
    source: redhat-operators
    sourceNamespace: openshift-marketplace
  loki:
    include: false
    namespace: openshift-logging
    operatorGroup: loki-operator
    package: loki-operator
    channel: stable
    source: redhat-operators
    sourceNamespace: openshift-marketplace
  lvm:
    include: false
    namespace: openshift-storage
    operatorGroup: openshift-storage-lvm
    package: lvms-operator
    channel: stable
    source: redhat-operators
    sourceNamespace: openshift-marketplace
  metallb:
    include: false
    namespace: metallb-system
    operatorGroup: metallb-system
    package: metallb-operator
    channel: stable
    source: redhat-operators
    sourceNamespace: openshift-marketplace
    clusterScoped: true
  mtv:
    include: false
    namespace: openshift-mtv
    operatorGroup: openshift-mtv
    package: mtv-operator
    channel: release-v2.6
    source: redhat-operators
    sourceNamespace: openshift-marketplace
  nmstate:
    include: false
    namespace: openshift-nmstate
    operatorGroup: openshift-nmstate
    package: kubernetes-nmstate-operator
    channel: stable
    source: redhat-operators
    sourceNamespace: openshift-marketplace
  node-feature-discovery:
    include: false
    namespace: openshift-nfd
    operatorGroup: openshift-nfd
    package: nfd
    channel: stable
    source: redhat-operators
    sourceNamespace: openshift-marketplace
  node-maintenance:
    include: false
    namespace: openshift-operators
    package: node-maintenance-operator
    channel: change-me
    source: redhat-operators
    sourceNamespace: openshift-marketplace
    skipNamespace: true
    skipOperatorGroup: true
  odf-operator:
    include: false
    namespace: openshift-storage
    operatorGroup: openshift-storage-operator
    package: odf-operator
    channel: stable
    source: redhat-operators
    sourceNamespace: openshift-marketplace
  openshift-pipelines:
    include: false
    namespace: openshift-operators
    package: openshift-pipelines-operator-rh
    channel: change-me
    source: redhat-operators
    sourceNamespace: openshift-marketplace
    skipNamespace: true
    skipOperatorGroup: true
  openshift-virtualization:
    include: false
    namespace: openshift-cnv
    operatorGroup: openshift-cnv
    package: kubevirt-hyperconverged
    channel: stable
    source: redhat-operators
    sourceNamespace: openshift-marketplace
  opentelemetry:
    include: false
    namespace: openshift-opentelemetry-operator
    operatorGroup: openshift-opentelemetry-operator
    package: opentelemetry-product
    channel: change-me
    source: redhat-operators
    sourceNamespace: openshift-marketplace
    clusterScoped: true
  quay:
    include: false
    namespace: quay-enterprise
    operatorGroup: quay-operator
    package: quay-operator
    channel: stable-3.11
    source: redhat-operators
    sourceNamespace: openshift-marketplace
  quay-bridge:
    include: false
    namespace: openshift-operators
    package: quay-bridge-operator
    channel: stable-3.11
    source: redhat-operators
    sourceNamespace: openshift-marketplace
    skipNamespace: true
    skipOperatorGroup: true
  servicemesh3:
    include: false
    namespace: openshift-operators
    package: servicemeshoperator3
    channel: change-me
    source: redhat-operators
    sourceNamespace: openshift-marketplace
    skipNamespace: true
    skipOperatorGroup: true
  tempo:
    include: false
    namespace: openshift-operators
    package: tempo-product
    channel: change-me
    source: redhat-operators
    sourceNamespace: openshift-marketplace
    skipNamespace: true
    skipOperatorGroup: true
  trident:
    include: false
    namespace: trident
    operatorGroup: trident-operator
    package: trident-operator
    channel: change-me
    source: certified-operators
    sourceNamespace: openshift-marketplace
    clusterScoped: true
  trusted-artifact-signer:
    include: false
    namespace: openshift-operators
    package: rhtas-operator
    channel: change-me
    source: redhat-operators
    sourceNamespace: openshift-marketplace
    skipNamespace: true
    skipOperatorGroup: true
  kyverno:
    include: false
    namespace: openshift-operators
    package: enterprise-kyverno
    channel: alpha
    source: certified-operators
    sourceNamespace: openshift-marketplace
    skipNamespace: true
    skipOperatorGroup: true
  gatekeeper:
    include: false
    namespace: openshift-operators
    package: gatekeeper-operator-product
    channel: stable
    source: redhat-operators
    sourceNamespace: openshift-marketplace
    skipNamespace: true
    skipOperatorGroup: true
  keycloak:
    include: false
    namespace: openshift-operators
    package: rhbk-operator
    channel: stable-v26
    source: redhat-operators
    sourceNamespace: openshift-marketplace
    skipNamespace: true
    skipOperatorGroup: true
