{{- if .Values.forkliftController.include }}
apiVersion: forklift.konveyor.io/v1beta1
kind: ForkliftController
metadata:
  name: {{ .Values.forkliftController.name }}
  namespace: {{ .Values.forkliftController.namespace }}
spec:
  feature_ui_plugin: true
  feature_validation: true
  feature_volume_populator: true
{{- end }}
