{{- if .Values.quayRegistry.include }}
apiVersion: v1
kind: Secret
metadata:
  name: quay-registry-config-bundle
  namespace: {{ .Values.quayRegistry.namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
type: Opaque
stringData:
  config.yaml: |
    SUPER_USERS:
    {{- range .Values.quayRegistry.superUsers }}
      - {{ . }}
    {{- end }}
    FEATURE_USER_INITIALIZE: {{ .Values.quayRegistry.userInitialize | default false }}
    FEATURE_USER_CREATION: false
    FEATURE_DIRECT_LOGIN: {{ not .Values.quayRegistry.keycloak.include }}
    FEATURE_GENERAL_OCI_SUPPORT: true
    FEATURE_SECURITY_SCANNER: true
    FEATURE_SECURITY_NOTIFICATIONS: true
    FEATURE_QUOTA_MANAGEMENT: true
    FEATURE_AUTO_PRUNE: true
    FEATURE_GARBAGE_COLLECTION: true
    FEATURE_PROXY_STORAGE: true
    FEATURE_TEAM_SYNCING: true
    FEATURE_NONSUPERUSER_TEAM_SYNCING_SETUP: false
    TEAM_RESYNC_STALE_TIME: 30m
    FEATURE_RATE_LIMITS: true
    FEATURE_ANONYMOUS_ACCESS: false
    FEATURE_ACTION_LOG_ROTATION: true
    ACTION_LOG_ARCHIVE_LOCATION: default
    DEFAULT_TAG_EXPIRATION: 2w
    TAG_EXPIRATION_OPTIONS:
      - 1d
      - 1w
      - 2w
      - 4w
      - 8w
      - 26w
      - 52w
    ALLOW_PULLS_WITHOUT_STRICT_LOGGING: false
    BROWSER_API_CALLS_XHR_ONLY: true
    DEFAULT_SYSTEM_REJECT_QUOTA_BYTES: 10737418240
    {{- if .Values.quayRegistry.keycloak.include }}
    KEYCLOAK_LOGIN_CONFIG:
      CLIENT_ID: {{ .Values.quayRegistry.keycloak.clientId }}
      CLIENT_SECRET: {{ .Values.quayRegistry.keycloak.clientSecret }}
      OIDC_SERVER: {{ .Values.quayRegistry.keycloak.oidcServer }}
      SERVICE_NAME: keycloak
      LOGIN_SCOPES:
        - openid
        - email
        - profile
      VERIFIED_EMAIL_CLAIM_NAME: email
    {{- end }}
{{- end }}
