{{- if .Values.quayRegistry.include }}
apiVersion: v1
kind: Secret
metadata:
  name: quay-registry-config-bundle
  namespace: {{ .Values.quayRegistry.namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
type: Opaque
stringData:
  config.yaml: |
    FEATURE_USER_INITIALIZE: true
    SUPER_USERS:
      - quayadmin
{{- end }}
