{{- if .Values.quayRegistry.include }}
apiVersion: v1
kind: Secret
metadata:
  name: quay-registry-config-bundle
  namespace: {{ .Values.quayRegistry.namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
type: Opaque
stringData:
  config.yaml: |
    FEATURE_USER_INITIALIZE: true
    SUPER_USERS:
      - quayadmin
    {{- if .Values.quayRegistry.keycloak.include }}
    FEATURE_DIRECT_LOGIN: false
    KEYCLOAK_LOGIN_CONFIG:
      CLIENT_ID: {{ .Values.quayRegistry.keycloak.clientId }}
      CLIENT_SECRET: {{ .Values.quayRegistry.keycloak.clientSecret }}
      OIDC_SERVER: {{ .Values.quayRegistry.keycloak.oidcServer }}
      SERVICE_NAME: keycloak
      LOGIN_SCOPES:
        - openid
        - email
        - profile
      VERIFIED_EMAIL_CLAIM_NAME: email
    {{- end }}
{{- end }}
