{{- if .Values.quayRegistry.include }}
apiVersion: quay.redhat.com/v1
kind: QuayRegistry
metadata:
  name: {{ .Values.quayRegistry.name }}
  namespace: {{ .Values.quayRegistry.namespace }}
spec:
  configBundleSecret: quay-registry-config-bundle
  components:
    - kind: clair
      managed: true
      overrides:
        resources:
          requests:
            cpu: 50m
            memory: 128Mi
          limits:
            cpu: 200m
            memory: 256Mi
    - kind: clairpostgres
      managed: true
      overrides:
        resources:
          requests:
            cpu: 50m
            memory: 128Mi
          limits:
            cpu: 200m
            memory: 256Mi
    - kind: postgres
      managed: true
      overrides:
        resources:
          requests:
            cpu: 50m
            memory: 128Mi
          limits:
            cpu: 200m
            memory: 512Mi
    - kind: objectstorage
      managed: true
    - kind: redis
      managed: true
      overrides:
        resources:
          requests:
            cpu: 50m
            memory: 32Mi
          limits:
            cpu: 100m
            memory: 64Mi
    - kind: horizontalpodautoscaler
      managed: false
    - kind: route
      managed: true
    - kind: mirror
      managed: false
    - kind: monitoring
      managed: false
    - kind: tls
      managed: true
    - kind: quay
      managed: true
      overrides:
        replicas: 1
        resources:
          requests:
            cpu: 100m
            memory: 256Mi
          limits:
            cpu: 500m
            memory: 512Mi
{{- end }}
