gatekeeper:
  include: false
  name: gatekeeper
  namespace: openshift-gatekeeper-system
  audit:
    auditChunkSize: 500
    logLevel: INFO
    replicas: 1
  validatingWebhook: Enabled
  mutatingWebhook: Disabled
  webhook:
    emitAdmissionEvents: Enabled
    logLevel: INFO
    replicas: 2
