{{- if .Values.provision.include }}
apiVersion: cluster.open-cluster-management.io/v1
kind: ManagedCluster
metadata:
  annotations:
    helm.sh/hook-weight: "370"
  labels:
    cloud: vSphere
    name: {{ .Values.cluster.name }}
    vendor: OpenShift
    environment: {{ .Values.cluster.environment }}
    fleet.openshift.io/operators-managed: "true"
    fleet.openshift.io/cluster-type: {{ .Values.cluster.operatorClusterType | default "prod" }}
    fleet.openshift.io/operator-profile: {{ .Values.cluster.operatorProfile | default "ocp-4.22" }}
    cluster.open-cluster-management.io/clusterset: vmware
  name: {{ .Values.cluster.name }}
spec:
  hubAcceptsClient: true
{{- end }}
