{{- range .Values.secrets }}
{{- if .include }}
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ .name }}
  namespace: {{ .namespace }}
spec:
  refreshInterval: {{ .refreshInterval | default "1h" }}
  secretStoreRef:
    name: {{ if .secretStoreRef }}{{ .secretStoreRef.name | default $.Values.secretStoreRef.name }}{{ else }}{{ $.Values.secretStoreRef.name }}{{ end }}
    kind: {{ if .secretStoreRef }}{{ .secretStoreRef.kind | default $.Values.secretStoreRef.kind }}{{ else }}{{ $.Values.secretStoreRef.kind }}{{ end }}
  target:
    name: {{ .name }}
    {{- if .type }}
    template:
      type: {{ .type }}
    {{- end }}
  data:
    {{- $vaultPath := .vault.path }}
    {{- range .vault.properties }}
    - secretKey: {{ .secretKey }}
      remoteRef:
        key: {{ $vaultPath }}
        property: {{ .property }}
    {{- end }}
{{- end }}
{{- end }}
