{{- if .Values.uiPlugins.logging.include }}
apiVersion: observability.openshift.io/v1alpha1
kind: UIPlugin
metadata:
  name: logging
spec:
  type: Logging
  logging:
    lokiStack:
      name: {{ .Values.uiPlugins.logging.lokiStack.name }}
    {{- with .Values.uiPlugins.logging.logsLimit }}
    {{- if gt (int .) 0 }}
    logsLimit: {{ . }}
    {{- end }}
    {{- end }}
    {{- with .Values.uiPlugins.logging.timeout }}
    timeout: {{ . }}
    {{- end }}
    {{- with .Values.uiPlugins.logging.schema }}
    schema: {{ . }}
    {{- end }}
{{- end }}
