{{- if .Values.l2Advertisements.include }}
{{- range .Values.l2Advertisements.advertisements }}
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: {{ .name }}
  namespace: {{ $.Values.metallb.namespace }}
spec:
  {{- if .ipAddressPools }}
  ipAddressPools:
    {{- range .ipAddressPools }}
    - {{ . }}
    {{- end }}
  {{- end }}
---
{{- end }}
{{- end }}
