{{- range $name, $operator := .Values.operators }}
{{- if and $operator.include (not $operator.skipNamespace) }}
apiVersion: v1
kind: Namespace
metadata:
  name: {{ $operator.namespace }}
  labels:
    app.kubernetes.io/managed-by: multi-cluster-config
    operator: {{ $name }}
---
{{- end }}
{{- end }}
