{{- range $name, $operator := .Values.operators }}
{{- if $operator.include }}
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: {{ $operator.operatorGroup }}
  namespace: {{ $operator.namespace }}
  labels:
    operator: {{ $name }}
{{- if eq $name "openshift-gitops" }}
spec: {}
{{- else }}
spec:
  targetNamespaces:
    - {{ $operator.namespace }}
{{- end }}
---
{{- end }}
{{- end }}
