# External ODF uses a StorageCluster as the primary configuration resource.
# The external Ceph connection details are cluster-specific and must be supplied
# separately by the external storage provider.
apiVersion: ocs.openshift.io/v1
kind: StorageCluster
metadata:
  name: ocs-external-storagecluster
  namespace: openshift-storage
spec:
  externalStorage:
    enable: true
  encryption:
    keyRotation:
      schedule: '@weekly'
  managedResources:
    cephBlockPools:
      reconcileStrategy: init
    cephCluster: {}
    cephDashboard: {}
    cephFilesystems: {}
    cephNonResilientPools: {}
    cephObjectStoreUsers: {}
    cephObjectStores:
      enableSTS: true
    cephRBDMirror: {}
    cephToolbox: {}
  multiCloudGateway:
    disableLoadBalancerService: true
