apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: platform
  namespace: openshift-gitops
spec:
  description: Provisioning, cluster configuration, and operator management
  sourceRepos:
    - https://github.com/albertogd/gitops-for-organizations.git
  destinations:
    - namespace: '*'
      server: '*'
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
