{{- if .Values.securedCluster.include }}
apiVersion: platform.stackrox.io/v1alpha1
kind: SecuredCluster
metadata:
  name: {{ .Values.securedCluster.name }}
  namespace: {{ .Values.securedCluster.namespace }}
spec:
  clusterName: {{ .Values.securedCluster.clusterName | default .Values.securedCluster.name }}
  {{- if .Values.securedCluster.centralEndpoint }}
  centralEndpoint: {{ .Values.securedCluster.centralEndpoint }}
  {{- end }}
  auditLogs:
    collection: Auto
  admissionControl:
    listenOnCreates: {{ .Values.securedCluster.admissionControl.listenOnCreates }}
    listenOnUpdates: {{ .Values.securedCluster.admissionControl.listenOnUpdates }}
    listenOnEvents: {{ .Values.securedCluster.admissionControl.listenOnEvents }}
    contactImageScanners: {{ .Values.securedCluster.admissionControl.contactImageScanners }}
  perNode:
    collector:
      collection: {{ .Values.securedCluster.collector.collection }}
      imageFlavor: {{ .Values.securedCluster.collector.imageFlavor }}
      forwardDeployedImageAnalysis: Inactive
    taintToleration: {{ .Values.securedCluster.taintToleration }}
  monitoring:
    openshift:
      enabled: true
{{- end }}
