{{- if .Values.central.include }}
apiVersion: platform.stackrox.io/v1alpha1
kind: Central
metadata:
  name: {{ .Values.central.name }}
  namespace: {{ .Values.central.namespace }}
spec:
  central:
    exposure:
      route:
        enabled: {{ .Values.central.exposure.route.enabled }}
      loadBalancer:
        enabled: {{ .Values.central.exposure.loadBalancer.enabled }}
        port: {{ .Values.central.exposure.loadBalancer.port }}
      nodePort:
        enabled: {{ .Values.central.exposure.nodePort.enabled }}
    persistence:
      persistentVolumeClaim:
        claimName: {{ .Values.central.persistence.claimName }}
    db:
      isEnabled: {{ .Values.central.db.isEnabled }}
      persistence:
        persistentVolumeClaim:
          claimName: {{ .Values.central.db.persistence.claimName }}
      resources:
        requests:
          cpu: {{ .Values.central.db.resources.requests.cpu }}
          memory: {{ .Values.central.db.resources.requests.memory }}
        limits:
          cpu: {{ .Values.central.db.resources.limits.cpu }}
          memory: {{ .Values.central.db.resources.limits.memory }}
    {{- if .Values.defaultTLS.include }}
    defaultTLSSecret:
      name: {{ .Values.defaultTLS.secretName }}
    {{- end }}
    telemetry:
      enabled: {{ .Values.central.telemetry.enabled }}
    {{- if .Values.oidc.include }}
    declarativeConfiguration:
      secrets:
        - name: acs-oidc-auth-provider
    {{- end }}
  monitoring:
    openshift:
      enabled: {{ .Values.central.monitoring.openshift.enabled }}
  egress:
    connectivityPolicy: {{ .Values.central.egress.connectivityPolicy }}
  scanner:
    scannerComponent: {{ .Values.central.scanner.scannerComponent }}
    analyzer:
      scaling:
        autoScaling: {{ .Values.central.scanner.analyzer.scaling.autoScaling }}
        minReplicas: {{ .Values.central.scanner.analyzer.scaling.minReplicas }}
        maxReplicas: {{ .Values.central.scanner.analyzer.scaling.maxReplicas }}
        replicas: {{ .Values.central.scanner.analyzer.scaling.replicas }}
    monitoring:
      exposeEndpoint: {{ .Values.central.scanner.monitoring.exposeEndpoint }}
  scannerV4:
    scannerComponent: {{ .Values.central.scannerV4.scannerComponent }}
    db:
      persistence:
        persistentVolumeClaim:
          claimName: {{ .Values.central.scannerV4.db.claimName }}
    indexer:
      scaling:
        autoScaling: {{ .Values.central.scannerV4.indexer.scaling.autoScaling }}
        minReplicas: {{ .Values.central.scannerV4.indexer.scaling.minReplicas }}
        maxReplicas: {{ .Values.central.scannerV4.indexer.scaling.maxReplicas }}
        replicas: {{ .Values.central.scannerV4.indexer.scaling.replicas }}
    matcher:
      scaling:
        autoScaling: {{ .Values.central.scannerV4.matcher.scaling.autoScaling }}
        minReplicas: {{ .Values.central.scannerV4.matcher.scaling.minReplicas }}
        maxReplicas: {{ .Values.central.scannerV4.matcher.scaling.maxReplicas }}
        replicas: {{ .Values.central.scannerV4.matcher.scaling.replicas }}
{{- end }}
