{{- if .Values.centralConsoleLink.include }}
apiVersion: console.openshift.io/v1
kind: ConsoleLink
metadata:
  name: acs-console-link
spec:
  applicationMenu:
    section: Security
  href: {{ .Values.centralConsoleLink.centralUrl | default (printf "https://central-stackrox.%s" .Values.cluster.baseDomain) | quote }}
  location: ApplicationMenu
  text: Advanced Cluster Security
{{- end }}
