{{- if .Values.defaultTLS.include }}
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ .Values.defaultTLS.secretName }}
  namespace: {{ .Values.central.namespace }}
spec:
  refreshInterval: {{ .Values.defaultTLS.refreshInterval }}
  secretStoreRef:
    name: {{ .Values.defaultTLS.secretStoreRef.name }}
    kind: {{ .Values.defaultTLS.secretStoreRef.kind }}
  target:
    name: {{ .Values.defaultTLS.secretName }}
    template:
      type: kubernetes.io/tls
  data:
    {{- range .Values.defaultTLS.vault.properties }}
    - secretKey: {{ .secretKey }}
      remoteRef:
        key: {{ $.Values.defaultTLS.vault.path }}
        property: {{ .property }}
    {{- end }}
{{- end }}
