{{- if .Values.central.include }}
apiVersion: platform.stackrox.io/v1alpha1
kind: Central
metadata:
  name: {{ .Values.central.name }}
  namespace: {{ .Values.central.namespace }}
spec:
  central:
    exposure:
      loadBalancer:
        enabled: false
        port: 443
      nodePort:
        enabled: false
      route:
        enabled: true
    db:
      isEnabled: Default
      persistence:
        persistentVolumeClaim:
          claimName: {{ .Values.central.persistence.claimName }}
      resources:
        requests:
          cpu: {{ .Values.central.db.resources.requests.cpu }}
          memory: {{ .Values.central.db.resources.requests.memory }}
        limits:
          cpu: {{ .Values.central.db.resources.limits.cpu }}
          memory: {{ .Values.central.db.resources.limits.memory }}
    persistence:
      persistentVolumeClaim:
        claimName: {{ .Values.central.persistence.claimName }}
    telemetry:
      enabled: true
  monitoring:
    openshift:
      enabled: true
  egress:
    connectivityPolicy: Online
  scanner:
    analyzer:
      scaling:
        autoScaling: Enabled
        maxReplicas: {{ .Values.central.scanner.autoScaling.maxReplicas }}
        minReplicas: {{ .Values.central.scanner.autoScaling.minReplicas }}
        replicas: {{ .Values.central.scanner.autoScaling.minReplicas }}
    monitoring:
      exposeEndpoint: Enabled
    scannerComponent: Enabled
  scannerV4:
    scannerComponent: Default
    db:
      persistence:
        persistentVolumeClaim:
          claimName: {{ .Values.central.scannerV4.db.claimName }}
    indexer:
      scaling:
        autoScaling: Enabled
        maxReplicas: {{ .Values.central.scannerV4.indexer.maxReplicas }}
        minReplicas: {{ .Values.central.scannerV4.indexer.minReplicas }}
        replicas: {{ .Values.central.scannerV4.indexer.minReplicas }}
    matcher:
      scaling:
        autoScaling: Enabled
        maxReplicas: {{ .Values.central.scannerV4.matcher.maxReplicas }}
        minReplicas: {{ .Values.central.scannerV4.matcher.minReplicas }}
        replicas: {{ .Values.central.scannerV4.matcher.minReplicas }}
{{- end }}
