{{- if and .Values.central.include .Values.central.initBundle.include .Values.central.initBundle.distributeAuth }}
apiVersion: policy.open-cluster-management.io/v1
kind: PlacementBinding
metadata:
  name: acs-central-auth
  namespace: {{ .Values.central.namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  placementRef:
    apiGroup: cluster.open-cluster-management.io
    kind: Placement
    name: acs-central-auth
  subjects:
    - apiGroup: policy.open-cluster-management.io
      kind: Policy
      name: acs-central-auth-distribution
{{- end }}
