quayNamespace:
  include: false
  name: quay-enterprise
quayRegistry:
  include: false
  name: registry
  namespace: quay-enterprise
  userInitialize: false
  superUsers:
    - quayadmin
  actionLogRotation:
    include: false
    archivePath: "action_log_archive/"
    archiveLocation: "local_us"
quayBridge:
  include: false
  quayHostname: ""
  oauthToken: ""
quayKeycloak:
  include: false
  oidcServer: ""
  clientId: "quay"
  clientSecret: ""
