{{- if .Values.pullSecrets.include }}
{{- range $ns := .Values.pullSecrets.namespaces }}
{{- range .secrets }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .name }}
  namespace: {{ $ns.name }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ printf `{"auths":{%q:{"username":%q,"password":%q,"email":%q,"auth":%q}}}` .registry .username .password .email (printf "%s:%s" .username .password | b64enc) | b64enc }}
{{- end }}
{{- end }}
{{- end }}
