{{- $op := index .Values.operators .Values.operatorName }}
{{- if and $op.include (not $op.skipOperatorGroup) }}
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: {{ $op.operatorGroup }}
  namespace: {{ $op.namespace }}
  labels:
    operator: {{ .Values.operatorName }}
{{- if $op.clusterScoped }}
spec: {}
{{- else }}
spec:
  targetNamespaces:
    - {{ $op.namespace }}
{{- end }}
{{- end }}
