{{- $op := index .Values.operators .Values.operatorName }}
{{- if $op.include }}
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: {{ $op.package }}
  namespace: {{ $op.namespace }}
  labels:
    operator: {{ .Values.operatorName }}
spec:
  name: {{ $op.package }}
  channel: {{ $op.channel }}
  source: {{ $op.source }}
  sourceNamespace: {{ $op.sourceNamespace }}
  installPlanApproval: Automatic
{{- end }}
