{{- if and .Values.consoleLink.include .Values.consoleLink.href }}
apiVersion: console.openshift.io/v1
kind: ConsoleLink
metadata:
  name: {{ .Values.consoleLink.name }}
spec:
  applicationMenu:
    section: {{ .Values.consoleLink.section }}
    imageURL: {{ .Values.consoleLink.imageURL | quote }}
  href: {{ .Values.consoleLink.href | quote }}
  location: {{ .Values.consoleLink.location }}
  text: {{ .Values.consoleLink.text | quote }}
{{- end }}
