{{- if and .Values.managedCluster.include .Values.managedCluster.klusterletAddonConfig.include }}
apiVersion: agent.open-cluster-management.io/v1
kind: KlusterletAddonConfig
metadata:
  name: {{ .Values.managedCluster.name }}
  namespace: {{ .Values.managedCluster.name }}
spec:
  clusterName: {{ .Values.managedCluster.name }}
  clusterNamespace: {{ .Values.managedCluster.name }}
  applicationManager:
    enabled: {{ .Values.managedCluster.klusterletAddonConfig.applicationManager }}
  certPolicyController:
    enabled: {{ .Values.managedCluster.klusterletAddonConfig.certPolicyController }}
  policyController:
    enabled: {{ .Values.managedCluster.klusterletAddonConfig.policyController }}
  searchCollector:
    enabled: {{ .Values.managedCluster.klusterletAddonConfig.searchCollector }}
{{- end }}
