{{- if and .Values.policies.include .Values.policies.imagePolicy.include }}
apiVersion: policy.open-cluster-management.io/v1
kind: Policy
metadata:
  name: {{ .Values.policies.imagePolicy.name }}
  namespace: {{ .Values.policies.namespace }}
  annotations:
    policy.open-cluster-management.io/standards: NIST SP 800-53
    policy.open-cluster-management.io/categories: CM Configuration Management
    policy.open-cluster-management.io/controls: CM-5 Access Restrictions for Change
spec:
  remediationAction: {{ .Values.policies.imagePolicy.remediationAction }}
  disabled: false
  policy-templates:
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: {{ .Values.policies.imagePolicy.name }}
        spec:
          remediationAction: {{ .Values.policies.imagePolicy.remediationAction }}
          severity: {{ .Values.policies.imagePolicy.severity }}
          object-templates:
            - complianceType: musthave
              objectDefinition:
                apiVersion: config.openshift.io/v1
                kind: Image
                metadata:
                  name: cluster
                spec:
                  registrySources:
                    allowedRegistries:
                      {{- toYaml .Values.policies.imagePolicy.allowedRegistries | nindent 22 }}
---
apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  name: {{ .Values.policies.imagePolicy.name }}-placement
  namespace: {{ .Values.policies.namespace }}
spec:
  clusterSelector:
    matchExpressions:
      {{- toYaml .Values.policies.imagePolicy.placement.clusterSelector.matchExpressions | nindent 6 }}
---
apiVersion: policy.open-cluster-management.io/v1
kind: PlacementBinding
metadata:
  name: {{ .Values.policies.imagePolicy.name }}-binding
  namespace: {{ .Values.policies.namespace }}
placementRef:
  apiGroup: apps.open-cluster-management.io
  kind: PlacementRule
  name: {{ .Values.policies.imagePolicy.name }}-placement
subjects:
  - apiGroup: policy.open-cluster-management.io
    kind: Policy
    name: {{ .Values.policies.imagePolicy.name }}
{{- end }}
