apiVersion: v1
kind: ConfigMap
metadata:
  name: sushy-ec2-config
data:
  instances.json: |
    {
      "instances": {
        "i-0f73a7c7762c67aa9": {
          "uuid": "master-0",
          "role": "master"
        },
        "i-0d36da9c2f8845411": {
          "uuid": "master-1",
          "role": "master"
        },
        "i-04a9b00e38df9f94b": {
          "uuid": "master-2",
          "role": "master"
        }
      }
    }
