apiVersion: v1
kind: Secret
metadata:
  name: sushy-ec2-aws-creds
type: Opaque
stringData:
  region: us-east-2
  aws_access_key_id: REPLACE_ME
  aws_secret_access_key: REPLACE_ME
  s3_bucket: REPLACE_ME
