{{- if .Values.securedCluster.include }}
apiVersion: platform.stackrox.io/v1alpha1
kind: SecuredCluster
metadata:
  name: {{ .Values.securedCluster.name }}
  namespace: {{ .Values.securedCluster.namespace }}
spec:
  clusterName: {{ .Values.cluster.name }}
  centralEndpoint: {{ .Values.securedCluster.centralEndpoint | default (printf "central-stackrox.%s:443" .Values.cluster.baseDomain) }}
  auditLogs:
    collection: {{ .Values.securedCluster.auditLogs.collection }}
  admissionControl:
    listenOnCreates: {{ .Values.securedCluster.admissionControl.listenOnCreates }}
    listenOnUpdates: {{ .Values.securedCluster.admissionControl.listenOnUpdates }}
    listenOnEvents: {{ .Values.securedCluster.admissionControl.listenOnEvents }}
    contactImageScanners: {{ .Values.securedCluster.admissionControl.contactImageScanners }}
    {{- if .Values.securedCluster.admissionControl.failurePolicy }}
    failurePolicy: {{ .Values.securedCluster.admissionControl.failurePolicy }}
    {{- end }}
  perNode:
    collector:
      collection: {{ .Values.securedCluster.perNode.collector.collection }}
      imageFlavor: {{ .Values.securedCluster.perNode.collector.imageFlavor }}
    taintToleration: {{ .Values.securedCluster.perNode.taintToleration }}
  {{- if .Values.securedCluster.scannerV4.scannerComponent }}
  scannerV4:
    scannerComponent: {{ .Values.securedCluster.scannerV4.scannerComponent }}
  {{- end }}
  {{- if .Values.securedCluster.network.policies }}
  network:
    policies: {{ .Values.securedCluster.network.policies }}
  {{- end }}
  {{- if .Values.securedCluster.customize.envVars }}
  customize:
    envVars:
      {{- toYaml .Values.securedCluster.customize.envVars | nindent 6 }}
  {{- end }}
  {{- if .Values.securedCluster.vmScanning }}
  vmScanning:
    enabled: true
  {{- end }}
  monitoring:
    openshift:
      enabled: {{ .Values.securedCluster.monitoring.openshift.enabled }}
{{- end }}
