storageCluster:
  include: false
  name: ocs-storagecluster
  namespace: openshift-storage
  deviceSets:
    count: 1
    replicas: 3
    storageSize: 512Gi
    storageClassName: gp3-csi
  encryption:
    clusterWide: true
  resourceProfile: balanced
csiTolerations:
  include: false
  tolerations:
    - key: node-role.kubernetes.io/master
      operator: Exists
      effect: NoSchedule
    - key: node-role.kubernetes.io/control-plane
      operator: Exists
      effect: NoSchedule
