{{- if and .Values.securedCluster.include (eq .Values.securedCluster.secretMode "preExisting") }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.securedCluster.secrets.admissionControl.name }}
  namespace: {{ .Values.securedCluster.namespace }}
  labels:
    certificate_key_name: admission-control-cert.pem
type: Opaque
data:
  admission-control-cert.pem: {{ .Values.securedCluster.secrets.admissionControl.cert | default "" | quote }}
  admission-control-key.pem: {{ .Values.securedCluster.secrets.admissionControl.key | default "" | quote }}
  ca.pem: {{ .Values.securedCluster.secrets.admissionControl.ca | default "" | quote }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.securedCluster.secrets.sensor.name }}
  namespace: {{ .Values.securedCluster.namespace }}
  labels:
    certificate_key_name: sensor-cert.pem
type: Opaque
data:
  sensor-cert.pem: {{ .Values.securedCluster.secrets.sensor.cert | default "" | quote }}
  sensor-key.pem: {{ .Values.securedCluster.secrets.sensor.key | default "" | quote }}
  ca.pem: {{ .Values.securedCluster.secrets.sensor.ca | default "" | quote }}
  acs-host: {{ .Values.securedCluster.secrets.sensor.acsHost | default "" | quote }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.securedCluster.secrets.collector.name }}
  namespace: {{ .Values.securedCluster.namespace }}
  labels:
    certificate_key_name: collector-cert.pem
type: Opaque
data:
  collector-cert.pem: {{ .Values.securedCluster.secrets.collector.cert | default "" | quote }}
  collector-key.pem: {{ .Values.securedCluster.secrets.collector.key | default "" | quote }}
  ca.pem: {{ .Values.securedCluster.secrets.collector.ca | default "" | quote }}
{{- end }}
