apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Dev cluster: GitOps agent only.
resources:
  - ../../../base/operators/openshift-gitops/install
  - ../../../base/operators/openshift-gitops/instances/default
  - operators-config.yaml

patches:
  - path: patches/gitops-minimal-patches.yaml

labels:
  - includeSelectors: false
    pairs:
      app.kubernetes.io/managed-by: multi-cluster-config
      app.kubernetes.io/part-of: platform-core

commonAnnotations:
  fleet.openshift.io/managed-by: gitops
  fleet.openshift.io/cluster-type: dev
