{{- if .Values.scanSetting.include }}
apiVersion: compliance.openshift.io/v1alpha1
kind: ScanSetting
metadata:
  name: {{ .Values.scanSetting.name }}
  namespace: {{ .Values.scanSetting.namespace }}
autoApplyRemediations: {{ .Values.scanSetting.autoApplyRemediations }}
rawResultStorage:
  pvAccessModes:
    {{- toYaml .Values.scanSetting.rawResultStorage.pvAccessModes | nindent 4 }}
  rotation: {{ .Values.scanSetting.rawResultStorage.rotation }}
  size: {{ .Values.scanSetting.rawResultStorage.size }}
  tolerations:
    {{- toYaml .Values.scanSetting.rawResultStorage.tolerations | nindent 4 }}
roles:
  {{- toYaml .Values.scanSetting.roles | nindent 2 }}
scanTolerations:
  {{- toYaml .Values.scanSetting.scanTolerations | nindent 2 }}
schedule: {{ .Values.scanSetting.schedule | quote }}
showNotApplicable: {{ .Values.scanSetting.showNotApplicable }}
strictNodeScan: {{ .Values.scanSetting.strictNodeScan }}
{{- end }}
