{{- range .Values.tailoredProfiles }}
{{- if .include }}
---
apiVersion: compliance.openshift.io/v1alpha1
kind: TailoredProfile
metadata:
  name: {{ .name }}
  namespace: {{ $.Values.scanSettingBinding.namespace }}
spec:
  title: {{ .title }}
  description: {{ .description | quote }}
  extends: {{ .extends }}
  {{- if .enableRules }}
  enableRules:
    {{- range .enableRules }}
    - name: {{ .name }}
      rationale: {{ .rationale | quote }}
    {{- end }}
  {{- end }}
  {{- if .disableRules }}
  disableRules:
    {{- range .disableRules }}
    - name: {{ .name }}
      rationale: {{ .rationale | quote }}
    {{- end }}
  {{- end }}
  {{- if .setValues }}
  setValues:
    {{- range .setValues }}
    - name: {{ .name }}
      rationale: {{ .rationale | quote }}
      value: {{ .value | quote }}
    {{- end }}
  {{- end }}
{{- end }}
{{- end }}
