{{- if .Values.multiClusterHub.include }}
apiVersion: operator.open-cluster-management.io/v1
kind: MultiClusterHub
metadata:
  name: {{ .Values.multiClusterHub.name }}
  namespace: {{ .Values.multiClusterHub.namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  availabilityConfig: {{ .Values.multiClusterHub.availabilityConfig }}
  disableHubSelfManagement: {{ .Values.multiClusterHub.disableHubSelfManagement }}
  localClusterName: {{ .Values.multiClusterHub.localClusterName }}
  {{- with .Values.multiClusterHub.overrides.components }}
  overrides:
    components:
      {{- toYaml . | nindent 6 }}
  {{- end }}
{{- end }}
