{{- if .Values.observabilityConsoleLink.include }}
{{- $href := .Values.observabilityConsoleLink.href | default (printf "https://grafana-open-cluster-management-observability.%s" .Values.cluster.baseDomain) }}
apiVersion: console.openshift.io/v1
kind: ConsoleLink
metadata:
  name: {{ .Values.observabilityConsoleLink.name }}
spec:
  applicationMenu:
    section: {{ .Values.observabilityConsoleLink.section }}
    imageURL: {{ .Values.observabilityConsoleLink.imageURL | quote }}
  href: {{ $href | quote }}
  location: {{ .Values.observabilityConsoleLink.location }}
  text: {{ .Values.observabilityConsoleLink.text | quote }}
{{- end }}
