{{- if .Values.multiClusterObservability.createNamespace }}
apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.multiClusterObservability.namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "-2"
  labels:
    openshift.io/cluster-monitoring: "true"
{{- end }}
